version: '3.8'

services:
  businessinsightcotainer:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=MicroBusinessInsight/MicroservHousesBusinessInsight.py
      - PYTHONPATH=/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    networks:
      - mytestnetwork

  geolocontainer:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=MicroGeoLoc/MicroservHousesGeoLoc.py
      - PYTHONPATH=/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001"]
    networks:
      - mytestnetwork

  neighborcontainer:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=MicroNeighbor/MicroservHousesNeighbor.py
      - PYTHONPATH=/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=5002"]
    networks:
      - mytestnetwork


  pricescontainer:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=MicroPrices/MicroservHousePrice.py
      - PYTHONPATH=/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=5003"]
    networks:
      - mytestnetwork


  housespecscontainer:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - FLASK_APP=MicroSpecs/MicroservHousesSpecs.py
      - PYTHONPATH=/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=5004"]
    networks:
      - mytestnetwork


  mainappcontainer:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - FLASK_APP=main.py
      - PYTHONPATH=/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=5005"]
    networks:
      - mytestnetwork

networks:
  mytestnetwork:
    driver: bridge